version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meet_development
    ports:
      - 5432:5432
  backend:
    build:
      context: packages/be/.
      dockerfile: Dockerfile
    volumes:
      - ./packages/be:/var/www
      - /var/www/node_modules
    environment:
      - NODE_ENV=docker
    ports:
      - 3000:3000
    depends_on:
      - postgres
  frontend:
    build:
      context: packages/fe/.
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=docker
    ports:
      - 8080:8080
    volumes:
      - ./packages/fe:/var/www/
      - /var/www/node_modules